name: Publish Docker Image to GitHub Packages

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

permissions:
  packages: write   # Grant permission to write to GitHub Packages
  contents: read    # Required to read the contents of the repository

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository Code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/my-docker-image:latest .

      - name: Push Docker Image to GitHub Packages
        run: |
          docker push ghcr.io/${{ github.repository }}/my-docker-image:latest
